### ISSUE TITLE
Galaxy Borders

### ISSUE THREAD

**Issue by BassXX** [jkroepke/2Moons#176]
Hi,

I wonder if it makes sense to make the Universe "closed loop" ? Like if you are at Galaxy 1 / System 1 and you go into the left direction, so you would be in Galaxy 9 / System 400.

It would allow the players at the borders to expand in two directions. Do you guys think this is easy to implement? And if yes, which files I need to consider for that?

Thanks!

**Comment by Hilarious001** [comment]
If you want to use ogame similar system (circular instead of linear) then you would probably need to edit flotten.js, and the page where it calculate the time of fly, can not say that from my work,
if you simply want to click and go from 9 -> 1, then you can simply make a if statement 

Example if $CurrentGalaxy == 9, then you go to galaxy 1

**Comment by jkroepke** [comment]
> Do you guys think this is easy to implement?Do you guys think this is easy to implement?
You have to change:
* fleet.js
* ShowGalaxyPage.class.php like (if $galaxyLeft && $galaxy = 1 then $galaxy = MAX_GALAXY)
* class.FleetFunctions.php (function GetTargetDistance)

Maybe I forgot something, I don't know.

**Comment by BassXX** [comment]
Thanks for the info guys, I will try to experiment a bit the next days when I find the time

**Comment by jkroepke** [comment]
Feel free to close it and reopen it, if you need more help!

If I close it, you can not reopen it.
