### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#179]
My Statistics Cronjob suddenly stoped working and says "Statistiken (Aktualisiert am: 01. Jan 1970, 01:00:00)". Next Update would have been yesterday, but it seems like it is waiting for the years to pass to do so. I searched high and low but couldnt find where it saves the date - any ideas? The Cronjob_Log is empty.

**Comment by Hilarious001** [comment]
Hello it saves the date in uni1_cronjob
you have each cronjob listed with as response nextTime
You can also change the time from admin panel => cronjobs => clicking on the arrow => setting time you want => save and then clear your cache 1 or 2 times with the admin panel clear cache menu

Regards

**Comment by terassiel** [comment]
It doesnt matter what time I set for the next Update... Somehow it set itself to 01. Jan 1970 and doesnt change back.

**Comment by jkroepke** [comment]
This is cron locked?
Any errors in error.log?

**Comment by terassiel** [comment]
Yes, Cron is locked, error log is clean.

**Comment by BassXX** [comment]
Probably you should unlock your cronjob then...

**Comment by terassiel** [comment]
Changes nothing

**Comment by jkroepke** [comment]
It is always statistic? Does a manuel trigger work? You can execute stats directly on acp

**Comment by terassiel** [comment]
It is only the statistics, all other cronjobs work just fine. A manual update works, but does not update the date on the statistics (which it used to do). Switching to unlocked does not work, when it gets to its next execution time it just switches back to locked. Using a backup of _cronjobs, _cronjobs_log, all relevant .php files did not solve the problem.

**Comment by Hilarious001** [comment]
The error log is your fault as you bugged your self the code of the error function (that part is fixed so you are able to see back your logs).
the reason why the cronjob is locked at your side is because all your users in uni1_users have hes id_planet set to 0, thats not logical, but thats an error you did your somewhere yourself, not reliated to the main pack of 2moons, you can fix it updating the id planets using users galaxy, system, planet information by selecting the id of those coords from uni1_planets with a good query and update it to users. but if you have relocate mod or the ability to delete home planets, then some players could still have id_planet set to 0, why people have id_planet set to 0 is not possile for me to say you
Regards

**Comment by terassiel** [comment]
I think I figuered out where the proplem originates from : 
USER ERROR: "Try to create a planet at position: 1:401:6!"
But I only have 400 Systems per galaxy... Which means every time a new user trys to create an account, the main planet can not be created resulting in id_planet = 0.

Now does anybody know why /includes/classes/PlayerUtil.class.php(192): PlayerUtil::createPlanet
does not jump to the next galaxy?

**Comment by jkroepke** [comment]
Possible fix: https://github.com/jkroepke/2Moons/pull/123

**Comment by Hilarious001** [comment]
Oh thats perfect it was the error i was telling jan some time ago

**Comment by jkroepke** [comment]
Did you have the coords of the latest main planet?

**Comment by terassiel** [comment]
Id_planet 2145, 1:400:9

**Comment by jkroepke** [comment]
k, thanks. I merged #123 so this error should be fixed.

**Comment by terassiel** [comment]
fixed and closed
