### ISSUE TITLE
External Auth 

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#209]
Hello @jkroepke can you maybe give me some information about how to use external auth function

Example.

I have login portal using a database. once you logged on the login portal you have the possibility to select the universe you want to play in (uni1, uni2 both with a new database)

If you click on login using uni1 it would check in the other database if you have a user like that registered, if yes then login if no then register and login using all info from the login portal

Same for uni2 with the 3th database and so on for each database, so each uni wil have hes personal database to not fill it with to much data

**Comment by jkroepke** [comment]
You have one database you want to using it as login source and multiple universe databases?

So the externalAuth Interface is verv very rudimentary. 

The Login URL should be shomethink like: index.php?page=externalAuth&method=hilarious. On includes/classes/extauth/hilarious.class.php, you have to create a class HilariousAuth. Checkout the externalAuth interface to get the required methods, use existing classs the openid (never tested) or facebook (has been work years ago) as example. To avoid that the user has to be reqister manually, getLoginData must be return always some data: `user.id, user.username, user.dpath, user.authlevel, user.id_planet`. If the player does not exists on your game. to have to register them in this context.
To do this: you can calling the ShowRegisterPage internally or execute the same steps on the ShowVerifyPage. `PlayerUtil::createPlayer` is your friend. getAccountData can be empty for you, because you want to skip the registration page.

I hope you understand my bad english. If not, I will try to use the translator next time ;-)

**Comment by Hilarious001** [comment]
Thanks for the help
i will try it out tonight and keep u updated, if i have any question

Regards

**Comment by Hilarious001** [comment]
Hello jan i have a small question, wich file does actualy call the config.php file to connect to the database
as i would have to switch the file to another name if i want to be able to use it in this context
Game files in public_html/game folder
Portal files in public_html/ folder
This avoid me to upload 2x my game in different folders if i could simply switch the database info connexion file in function of the uni selected to login

**Comment by jkroepke** [comment]
Did you have different Subdomains for your universers?

You can simply do somethink like if DOMAIN = "A" { DB CONNECTIONS FOR UNI1 } elseif { DB CONNECTIONS FOR UNI2 } and so on. You could also use game/uni1 and game/uni2. $_SERVER['REDIRECT_UNI'] should contain the 1 or 2, if you are using apache. https://github.com/jkroepke/2Moons/blob/master/.htaccess#L47

**Comment by Hilarious001** [comment]
Ok i found a way to do what i wanted
i have one small problem
world1.mydomain.com/game.php says it doesnt exist
mydomain.com/world1/game.php works perfectly
What could cause this ?

Regards

**Comment by Hilarious001** [comment]
Nvm all sorted out
Regards
