### ISSUE TITLE
Feature acs profit share

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#236]
Hello since jan said he could add feature interesting for the game, maybe this is one ? i made it under 2moons PDO version
There is a manual (entering lost fleet for each player) and an automated version when entering the battle RID where even the name of the players are auto loaded, otherwise its really hard to know how to share profit in case of ACS mission since lost amount are grouped.

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img15.hostingpics.net/pics/601532Sanstitre.png" border="0" alt="Hebergeur d'image" /></a>

**Comment by jkroepke** [comment]
I do not understand it. Can you more explain it?

**Comment by OzanKurt** [comment]
Did you create a pull request?

**Comment by Hilarious001** [comment]
Helo no i did not create a pull request.

Really easy you make a group attack, 

@OzanKurt & Hilarious001 vs @jkroepke 

Attackers side win but lost alot of units because jkroepke was really strong.
You do not know how much units each attackers lost because the amounts are grouped.
With this feature, you can enter the lost fleets manualy, or simply enter the battle RID

And it wil enter for each attacker their names, their lost units, their deut compsumption to get there.
All you have to enter manualy is the debris recycled

And it show you how much profit you get / user so you know how to share exactly the debris in a fast way

Instead of taking a calculator and doing 1.000.000.000 LF * 3.000 metal = xxx to be able to share it

Regards

**Comment by jkroepke** [comment]
Ah okay.

Why we not improve the message which we are send to the players?

Hilarious001 <notifications@github.com<mailto:notifications@github.com>> schrieb am Sa., 9. Juli 2016, 18:04:

Helo no i did not create a pull request.

Really easy you make a group attack,

@OzanKurt<https://github.com/OzanKurt> & Hilarious001 vs @jkroepke<https://github.com/jkroepke>

Attackers side win but lost alot of units because jkroepke was really strong.
You do not know how much units each attackers lost because the amounts are grouped.
With this feature, you can enter the lost fleets manualy, or simply enter the battle RID

And it wil enter for each attacker their names, their lost units, their deut compsumption to get there.
All you have to enter manualy is the debris recycled

And it show you how much profit you get / user so you know how to share exactly the debris in a fast way

Instead of taking a calculator and doing 1.000.000.000 LF * 3.000 metal = xxx to be able to share it

Regards

**Comment by OzanKurt** [comment]
Great!

I would like to see the code, please create a PR and lets have a look at it together for optimizations.

**Comment by Hilarious001** [comment]
@jkroepke because it will not say you how to share de debris with all attackers.

At the end of the picture you can see total and average

Total = total profit from battle
Average = what each attacker should keep as profit to have all the same

**Comment by OzanKurt** [comment]
Ozan & Jeremy vs Jan

Ozan - 1 Small Cargo
Jeremy - 100000 Light Fighter

The loot should not be shared equally. Is that the case?

**Comment by Hilarious001** [comment]
Thats incase you use 100% ogame rules

I will add PR later in the day it cas easily be adapted to share in function of the user fleets point send in the battle.

I also made the Spacedock, the outlaw status and the honour system points from ogame  

http://forum.xterium.space/topic/180-new-features-honour-points-and-targets/
http://forum.xterium.space/topic/179-new-building-xterium-dock/
http://forum.xterium.space/topic/181-tuto-outlaw-status/
