### ISSUE TITLE
Facebook registration

### ISSUE THREAD

**Issue by scarecr0w12** [jkroepke/2Moons#244]
I am unable to get the FB Registration working, keeps erroring out with too many redirects.

**Comment by Hilarious001** [comment]
Do you show the popup to ask the right of email and public_profile?
I had the same problem when i wanted to use it on facebook with no login screen and register screen; finaly fixed, but the problem was the right issue not asked

So instead of the previous way i had
=> facebook => game
=> facebook => facebook request on my website => facebook ingame (no login, no register)

**Comment by ogamemaster** [comment]
**Hilarious00**   why not share your version?

**Comment by scarecr0w12** [comment]
Mine goes nowhere as it errors out giving the too many redirects error page. so no it doesn't

**Comment by Hilarious001** [comment]
Because i use my own version and i am not forced to post my own code on something that has nothing to do with it, it its usefull and use the 2moons code, then i make a pull request, if its my own code to make something work, then i am not forced to share

You can find more help on the facebook developers page itself

Regards

**Comment by jkroepke** [comment]
I will close this issue. I dont havr the time to relearn the facebook API nor to create a test environment to test the facebook ingration. From m side, i wont support the fb Integration in 2moons anymore.

Fell free to still discuss this issue after I close it.
