### ISSUE TITLE
Holiday Modus

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#255]
User does not come back from Holiday.
Could we set a max holiday days?

**Comment by jkroepke** [comment]
Normally, user would be deleted after 30 days.

**Comment by OzanKurt** [comment]
isn't it inactives?

**Comment by lilmnm-kamikaze-** [comment]
Yes and no. 

If an account is inactive for 30 days such as an account that is in holiday as the normal inactive timers doesn't apply. its is deemed inactive and is taken out of holiday and removed. Which is why i tell my users to at least sign in once a week as a check in type of thing. I also have a limit on the length they can be in holiday mode at 30 days with a week cool down before they can enter it again to keep people from abusing it.
