### ISSUE TITLE
Fix for Tech.php for french translate

### ISSUE THREAD

**Issue by zato369** [jkroepke/2Moons#259]
here de tech.php for french translate fixed
[TECH.zip](https://github.com/jkroepke/2Moons/files/436721/TECH.zip)

**Comment by BigTwoProduction** [comment]
Hello @zato369 ,

I understand why you propose this "fix", it's because this issue you've close [https://github.com/jkroepke/2Moons/issues/257](url) isn't it ?

But i see two problem the second translation you've made is not the right translation. Both files are very different. Many expression and many word has change.....

So by this way i'm not agree if you keep at the top of the file my name or please add "Version 1.1 by zato369".
But we can discuss why you made as mush change.
For your problem, it's due to accent but on my server there is no error with encode accent. So i think is our configuration server's. So actuality by the first version no error for me.

@jkroepke Can you tell me (us) if i'm in the right way by encode accent in language php files ?
And why these files made by me work for me and no really for @zato369 

Best regards,
Jordan.

**Comment by jkroepke** [comment]
Does not make sense. In #257 , you report a problem. The technical issue is, the language key sys_stat_mess has too few params. sys_stat_mess is in the FLEET.php. I compared fr with de and both languages has 7 parameter.

@zato369 Please explain, what did you want to fix?

@BigTwoProduction my english is not so good. What did you mean with "encode accent" ? Did you mean the langauge accent or the file encoding?

**Comment by BigTwoProduction** [comment]
Hello,

By "accent encoding" I means this,

In French language we have characters like that "é,à,è..." so perhaps I'm in the wrong way but I encode them like that.

```
é=&eacute;
à=&agrave;
```
So for [sys_stat_mess] or all other translation I encode accent, why ? Because on my server when accent was not encode that make many error. According to the HTML rules for accent.

@jkroepke I'm in the right way no mistake ?

Best regards,
Jordan.

**Comment by jkroepke** [comment]
@BigTwoProduction It's okay. but it is not required. If you encode your file with UTF-8, you can use the normal special chars. It works in russian, too.

Example: https://github.com/jkroepke/2Moons/blob/master/language/ru/INGAME.php

**Comment by BigTwoProduction** [comment]
@jkroepke Ok thanks for this useful information ! 
I will re-work on accent in FR files for the next "PR" to improve rules encode.

@zato369 We waiting you to explain us why you made change ?

**Comment by jkroepke** [comment]
You can also add yourself to the french translators

https://github.com/jkroepke/2Moons/blob/master/styles/templates/adm/OverviewBody.tpl#L141
