### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Hexeus** [jkroepke/2Moons#296]
USER ERROR
Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lostunits = lostunits + '0', desunits = desunits + '0' WHERE id IN (3)' at line 5

Query-Code:UPDATE uni1_users SET `loos` = `loos` + 1, kbmetal = kbmetal + 0, kbcrystal = kbcrystal + 0,K lostunits = lostunits + 0, desunits = desunits + 0 WHERE id IN (3);
File: /includes/classes/Database.class.php
Line: 123
URL: http://2moons.hexeus.com/game.php?page=raport&raport=f5e27af9bf1ff5a7eb0644e347cb6491
PHP-Version: 5.6.30
PHP-API: litespeed
MySQL-Client-Version: 5.6.35
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(174): Database->_query('UPDATE %%USERS%...', Array, 'update')
#1 /includes/classes/missions/MissionCaseDestruction.class.php(599): Database->update('UPDATE %%USERS%...', Array)
#2 /includes/classes/class.FlyingFleetHandler.php(80): MissionCaseDestruction->TargetEvent()
#3 /includes/FleetHandler.php(31): FlyingFleetHandler->run()
#4 /includes/common.php(140): require('FILEPATH ...')
#5 /game.php(24): require('FILEPATH ...')
#6 {main}

**Comment by jkroepke** [comment]
Hi.

did you modified your code? The Problem is there is a 'K' in your code which is not the the original.

https://github.com/jkroepke/2Moons/blob/master/includes/classes/missions/MissionCaseDestruction.class.php#L575

**Comment by Hexeus** [comment]
I have not edited the code. I downloaded it and installed it. The only thing I do is mess with the planet values in the Database since I get an error when trying to move planets/moons to new coords.

**Comment by jkroepke** [comment]
Removing the K at this point should fix you issue. It happend while destory
moon. So you can reproduce it.

Am 28.05.2017 um 21:50 schrieb Hexeus <notifications@github.com>:

I have not edited the code. I downloaded it and installed it. The only
thing I do is mess with the planet values in the Database since I get an
error when trying to move planets/moons to new coords.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jkroepke/2Moons/issues/296#issuecomment-304536109>, or mute
the thread

**Comment by jkroepke** [comment]
Hum, okay. 
I didn't see the error in my code. https://github.com/jkroepke/2Moons/blob/master/includes/classes/missions/MissionCaseDestruction.class.php#L589

**Comment by jkroepke** [comment]
Should be resolved now. Sorry about that trouble.
