### ISSUE TITLE
3rd party account creation or REST API?

### ISSUE THREAD

**Issue by VidYen** [jkroepke/2Moons#358]
I have a user who is insterested in using this with one of my website plugins.

However, my software is WordPress based, so I don't think it will be that easy translate users from wordpress sql to this.

But is there a REST API or some type of system where 3rd party sites can communicate with a website using this?

What they want to is have users mine crypto currency or watch ads and then that earns in game currency or resources?

Is there already an API like that or would that have to be done from scratch?

Thanks!

-Felty

**Comment by jkroepke** [comment]
> But is there a REST API or some type of system where 3rd party sites can communicate with a website using this?

There is an indirect mechanism to connect system with external user management. The past I create a integration with phpbb, so 2Moons used the phpbb user base to authenticate the user inside the system.

The mechanism is called "ExternalAuth" inside 2Moons. https://github.com/jkroepke/2Moons/blob/master/includes/pages/login/ShowExternalAuthPage.class.php and its pluggable. For can find examples here:

https://github.com/jkroepke/2Moons/tree/master/includes/classes/extauth

As example there are two integration. Facebook should not work anymore because they the apis. OpenID is dead.

The cleanst way to integration 2Moons with somethink like Wordpress would be via OAuth2. Its a well defined protocol, you can add a OAuth server to wordpress with (https://de.wordpress.org/plugins/oauth2-provider/) and you had to write an oauth2 client itself.

The other dirty method would be to get some info from the wordpress db directly. I did this for the phpbb integration, too but i do not recommend this today.

**Comment by VidYen** [comment]
Thanks! I have another question but technically a different issue.
